=== darshanramu/CompanyDB_XML_XQUERY/company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="XYZ_COMPANY">
		<xs:annotation>
			<xs:documentation>XML Schema for XYZ Company</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Department" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="deptID">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[A-Z]{3}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="deptName" type="xs:string"/>
							<xs:element name="deptAddr" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Division" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="divID" type="xs:string"/>
							<xs:element name="divName" type="xs:string"/>
							<xs:element name="divPhone">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[1-9]{1}[0-9]{2}\-[0-9]{3}\-[0-9]{4}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="housedDeptID" type="xs:string"/>
							<xs:element name="managerEmpID" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Employee" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="empID" type="xs:string"/>
							<xs:element name="empName" type="xs:string"/>
							<xs:element name="empPhone" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[1-9]{1}[0-9]{2}\-[0-9]{3}\-[0-9]{4}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="empOffice" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="WorksFor" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="divID" type="xs:string"/>
							<xs:element name="empID" type="xs:string"/>
							<xs:element name="percentTime" type="xs:integer"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="deptID">
			<xs:selector xpath="Department/deptID"/>
			<xs:field xpath="."/>
		</xs:key>
		<xs:key name="divID">
			<xs:selector xpath="Division/divID"/>
			<xs:field xpath="."/>
		</xs:key>
		<xs:key name="empID">
			<xs:selector xpath="Employee/empID"/>
			<xs:field xpath="."/>
		</xs:key>
		<xs:keyref name="housedDeptID" refer="deptID">
			<xs:selector xpath="Division/housedDeptID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="managerEmpID" refer="empID">
			<xs:selector xpath="Division/managerEmpID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="WorksFor_empID" refer="empID">
			<xs:selector xpath="WorksFor/empID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="WorksFor_divID" refer="divID">
			<xs:selector xpath="WorksFor/divID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:key name="WorksForPK">
			<xs:selector xpath="WorksFor"/>
			<xs:field xpath="divID"/>
			<xs:field xpath="empID"/>
		</xs:key>
	</xs:element>
</xs:schema>

=== darshanramu/CompanyDB_XML_XQUERY/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="company.xsl" ?>
<XYZ_COMPANY xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="company.xsd">
	<Department>
		<deptID>ADM</deptID>
		<deptName>Admin</deptName>
		<deptAddr>LA</deptAddr>
	</Department>
	<Department>
		<deptID>FIN</deptID>
		<deptName>Finance</deptName>
		<deptAddr>LA</deptAddr>
	</Department>
	<Department>
		<deptID>SER</deptID>
		<deptName>Services</deptName>
		<deptAddr>LA</deptAddr>
	</Department>
	<Department>
		<deptID>OPR</deptID>
		<deptName>Operations</deptName>
		<deptAddr>LA</deptAddr>
	</Department>
	<Department>
		<deptID>BUS</deptID>
		<deptName>Business</deptName>
		<deptAddr>LA</deptAddr>
	</Department>
	<Division>
		<divID>div1</divID>
		<divName>HR</divName>
		<divPhone>346-232-3242</divPhone>
		<housedDeptID>ADM</housedDeptID>
		<managerEmpID>4</managerEmpID>
	</Division>
	<Division>
		<divID>div2</divID>
		<divName>Recruitment</divName>
		<divPhone>346-232-3243</divPhone>
		<housedDeptID>ADM</housedDeptID>
		<managerEmpID>1</managerEmpID>
	</Division>
	<Division>
		<divID>div3</divID>
		<divName>SysAd</divName>
		<divPhone>346-232-3244</divPhone>
		<housedDeptID>ADM</housedDeptID>
		<managerEmpID>3</managerEmpID>
	</Division>
	<Division>
		<divID>div4</divID>
		<divName>Payroll</divName>
		<divPhone>346-232-3245</divPhone>
		<housedDeptID>FIN</housedDeptID>
		<managerEmpID>5</managerEmpID>
	</Division>
	<Division>
		<divID>div5</divID>
		<divName>Accounting</divName>
		<divPhone>346-232-3246</divPhone>
		<housedDeptID>FIN</housedDeptID>
		<managerEmpID>5</managerEmpID>
	</Division>
	<Division>
		<divID>div6</divID>
		<divName>Networking</divName>
		<divPhone>346-232-3247</divPhone>
		<housedDeptID>SER</housedDeptID>
		<managerEmpID>2</managerEmpID>
	</Division>
	<Division>
		<divID>div7</divID>
		<divName>SaaS</divName>
		<divPhone>346-232-3248</divPhone>
		<housedDeptID>SER</housedDeptID>
		<managerEmpID>2</managerEmpID>
	</Division>
	<Division>
		<divID>div8</divID>
		<divName>Security</divName>
		<divPhone>346-232-3249</divPhone>
		<housedDeptID>SER</housedDeptID>
		<managerEmpID>1</managerEmpID>
	</Division>
	<Division>
		<divID>div9</divID>
		<divName>Convergence</divName>
		<divPhone>346-232-3250</divPhone>
		<housedDeptID>SER</housedDeptID>
		<managerEmpID>1</managerEmpID>
	</Division>
	<Division>
		<divID>div10</divID>
		<divName>Sales</divName>
		<divPhone>346-232-3251</divPhone>
		<housedDeptID>OPR</housedDeptID>
		<managerEmpID>1</managerEmpID>
	</Division>
	<Division>
		<divID>div11</divID>
		<divName>Marketing</divName>
		<divPhone>346-232-3252</divPhone>
		<housedDeptID>OPR</housedDeptID>
		<managerEmpID>4</managerEmpID>
	</Division>
	<Division>
		<divID>div12</divID>
		<divName>Engineering</divName>
		<divPhone>346-232-3253</divPhone>
		<housedDeptID>OPR</housedDeptID>
		<managerEmpID>4</managerEmpID>
	</Division>
	<Division>
		<divID>div13</divID>
		<divName>Business Development</divName>
		<divPhone>346-232-3254</divPhone>
		<housedDeptID>BUS</housedDeptID>
		<managerEmpID>1</managerEmpID>
	</Division>
	<Division>
		<divID>div14</divID>
		<divName>Business Analysis</divName>
		<divPhone>346-232-3255</divPhone>
		<housedDeptID>BUS</housedDeptID>
		<managerEmpID>1</managerEmpID>
	</Division>
	<Employee>
		<empID>1</empID>
		<empName>PSmith</empName>
		<empPhone>243-235-3253</empPhone>
		<empOffice>LA</empOffice>
	</Employee>
	<Employee>
		<empID>2</empID>
		<empName>Wong</empName>
		<empPhone>224-234-9065</empPhone>
		<empOffice>LA</empOffice>
	</Employee>
	<Employee>
		<empID>3</empID>
		<empName>Jack</empName>
		<empPhone>243-235-4566</empPhone>
		<empOffice>LA</empOffice>
	</Employee>
	<Employee>
		<empID>4</empID>
		<empName>Anne</empName>
		<empPhone>324-876-3768</empPhone>
		<empOffice>LA</empOffice>
	</Employee>
	<Employee>
		<empID>5</empID>
		<empName>Ben</empName>
		<empPhone>453-249-3275</empPhone>
		<empOffice>LA</empOffice>
	</Employee>
	<Employee>
		<empID>6</empID>
		<empName>Monica</empName>
		<empPhone>935-487-3859</empPhone>
		<empOffice>LA</empOffice>
	</Employee>
	<Employee>
		<empID>7</empID>
		<empName>Jennifer</empName>
		<empPhone>935-487-3869</empPhone>
		<empOffice>LA</empOffice>
	</Employee>
	<Employee>
		<empID>8</empID>
		<empName>Mary</empName>
		<empPhone>932-487-3859</empPhone>
		<empOffice>LA</empOffice>
	</Employee>
	<WorksFor>
		<divID>div1</divID>
		<empID>4</empID>
		<percentTime>60</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div2</divID>
		<empID>4</empID>
		<percentTime>10</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div3</divID>
		<empID>4</empID>
		<percentTime>10</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div13</divID>
		<empID>4</empID>
		<percentTime>5</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div14</divID>
		<empID>4</empID>
		<percentTime>5</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div2</divID>
		<empID>5</empID>
		<percentTime>10</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div3</divID>
		<empID>5</empID>
		<percentTime>10</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div4</divID>
		<empID>5</empID>
		<percentTime>50</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div5</divID>
		<empID>5</empID>
		<percentTime>30</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div2</divID>
		<empID>3</empID>
		<percentTime>20</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div3</divID>
		<empID>3</empID>
		<percentTime>20</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div8</divID>
		<empID>3</empID>
		<percentTime>60</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div2</divID>
		<empID>6</empID>
		<percentTime>10</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div3</divID>
		<empID>6</empID>
		<percentTime>10</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div6</divID>
		<empID>6</empID>
		<percentTime>60</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div7</divID>
		<empID>6</empID>
		<percentTime>20</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div2</divID>
		<empID>1</empID>
		<percentTime>5</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div3</divID>
		<empID>1</empID>
		<percentTime>5</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div6</divID>
		<empID>1</empID>
		<percentTime>15</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div8</divID>
		<empID>1</empID>
		<percentTime>5</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div10</divID>
		<empID>1</empID>
		<percentTime>60</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div13</divID>
		<empID>1</empID>
		<percentTime>5</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div9</divID>
		<empID>1</empID>
		<percentTime>3</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div14</divID>
		<empID>1</empID>
		<percentTime>2</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div2</divID>
		<empID>2</empID>
		<percentTime>10</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div3</divID>
		<empID>2</empID>
		<percentTime>10</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div6</divID>
		<empID>2</empID>
		<percentTime>30</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div7</divID>
		<empID>2</empID>
		<percentTime>10</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div1</divID>
		<empID>2</empID>
		<percentTime>10</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div8</divID>
		<empID>2</empID>
		<percentTime>15</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div4</divID>
		<empID>2</empID>
		<percentTime>15</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div7</divID>
		<empID>7</empID>
		<percentTime>90</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div2</divID>
		<empID>7</empID>
		<percentTime>5</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div3</divID>
		<empID>7</empID>
		<percentTime>5</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div11</divID>
		<empID>8</empID>
		<percentTime>90</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div2</divID>
		<empID>8</empID>
		<percentTime>5</percentTime>
	</WorksFor>
	<WorksFor>
		<divID>div3</divID>
		<empID>8</empID>
		<percentTime>5</percentTime>
	</WorksFor>
</XYZ_COMPANY>
